language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

os:
 - linux

before_install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - $HOME/gopath/bin/goveralls -repotoken 1l94YpBIBq16rpjgbMWJxneisz6Q0Q273 -v
